name: Flutter APKs
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: echo "${{ secrets.ENV_FILE }}" > .env
          

      - name: Set up SSH
        run: |
          # Crée un répertoire .ssh
          mkdir -p ~/.ssh
          # Ajoute la clé privée SSH stockée dans le secret GitHub
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          # Définit les permissions pour la clé privée SSH
          chmod 600 ~/.ssh/id_rsa
          # Ajoute le serveur distant à la liste des hôtes connus
          ssh-keyscan -H 82.66.110.4 >> ~/.ssh/known_hosts

      - name: Build Flutter APKs
        uses: subosito/flutter-action@v2.16.0
        with:
          flutter-version: 3.22.0
      - run: flutter config --enable-web
      - run: flutter pub get
      - run: flutter build apk --release --obfuscate --split-debug-info=debug_info/ --split-per-abi

      - name: Deploy application via SSH
        run: | 
          scp -r build/app/outputs/flutter-apk/* romain@82.66.110.4:/var/www/flutter_apk
